# Adapted from https://github.com/sbt/sbt-native-packager/blob/master/appveyor.yml
version: '{build}'
os: Windows Server 2012

#  To make the extended ascii characters work on Windows
#  we need to set string encoding for jvm to utf-8 on windows
environment:
  SBT_OPTS: -Dfile.encoding=UTF8
  JAVA_OPTS: -Dfile.encoding=UTF8
  nodejs_version: "4.5.0"
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

install:
  - ps: |
      Add-Type -AssemblyName System.IO.Compression.FileSystem
      if (!(Test-Path -Path "C:\sbt" )) {
        (new-object System.Net.WebClient).DownloadFile(
          'https://dl.bintray.com/sbt/native-packages/sbt/0.13.13/sbt-0.13.13.zip',
          'C:\sbt-bin.zip'
        )
        [System.IO.Compression.ZipFile]::ExtractToDirectory("C:\sbt-bin.zip", "C:\sbt")
      }
  - ps: Install-Product node $env:nodejs_version
  - cmd: SET PATH=C:\sbt\sbt\bin;%JAVA_HOME%\bin;%PATH%
  - cmd: SET SBT_OPTS=-XX:MaxPermSize=2g -Xmx4g
build_script:
  - sbt clean compile

test_script:
  - sbt test
